DATASET:
  DATA_SET: Houston2018
  CATEGORY_NUM: 20
  CROP_SIZE: 32
  PATCHES_NUM: 4000
  TRAIN_NUM: 30
  VAL_NUM: 10
SOLVER:
  TRAIN:
    MAX_ITER: 600000
  CHECKPOINT_PERIOD: 500
  VALIDATE_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 8
  BATCH_SIZE_TRAIN: 16
  BATCH_SIZE_TEST: 16
MODEL:
  META_ARCHITECTURE: trainnet
OUTPUT_DIR: output
# OUTPUT_DIR: ../autodl-tmp/output

