DATASET:
  DATA_SET: XiongAn
  CATEGORY_NUM: 20
  CROP_SIZE: 25
  PATCHES_NUM: 400
  TRAIN_NUM: 30
  VAL_NUM: 10
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 20
MODEL:
  META_ARCHITECTURE: searchnet
  AFFINE: False
DATALOADER:
  BATCH_SIZE_TRAIN: 1
  BATCH_SIZE_TEST: 1
  NUM_WORKERS: 4
  DATA_LIST_DIR: ./sample
SOLVER:
  MAX_EPOCH: 200
  CHECKPOINT_PERIOD: 1

OUTPUT_DIR: output